### ISSUE TITLE
Could not find multidex.jar (com.android.support:multidex:1.0.2). Error

### ISSUE THREAD

**Issue by kenziy** [paulstelzer/cordova-plugin-admob-mediation#1]
Hey guys

I just try to install this with cordova-plugin-admob-free and I got this error

 `
Could not find multidex.jar (com.android.support:multidex:1.0.2).
`
I have fresh installed cordova having only cordova-plugin-admob-free and cordova-plugin-admob-mediation plugins

**Comment by paulstelzer** [comment]
Normally it should install the peer dependency "cordova-plugin-enable-multidex", too. 

Seems that you have to add it manually:

`cordova plugin add cordova-plugin-enable-multidex`

**Comment by kenziy** [comment]
Hello @paulstelzer 

I tried doing the installation manually but it seems that error is still showing.

Here is a screenshot
https://www.screencast.com/t/mPkHpCotr7

**Comment by paulstelzer** [comment]
That seems to be an error with the multidex path. You can remove the multidex from my plugin and make it without it. Multidex is just relevant if you have more than 65k methods

**Comment by kenziy** [comment]
Hello @paulstelzer 

I'm still having a problem with this. To be honest I'm new at cordova. And the solution you mentioned above I can't make it work. Do you have a full working example of your plugin w/ cordova-plugin-admob-free? That will be a great help to us

Thanks

**Comment by paulstelzer** [comment]
I have added a new package. This not includes multidex. Please remove the other plugin via cordova and remove the plugins and platform folder to start clean.

`cordova plugin add cordova-plugin-admob-mediation-no-multidex`

Btw, my plugin only include unity and facebook because I use this networks for my apps. If you only want to use Unity or any other, please take a look at the packages of lycwed (e.g. https://github.com/lycwed/lycwed-cordova-plugin-admob-unityads )

**Comment by kenziy** [comment]
Thank you @paulstelzer now the issue was resolved and Google reward videos are now running in my apps 

Thank you
